service: demo-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: 'dev'
  region: "ap-southeast-1"
  s3:
    bucketOne:
      name: demo-johndev4-photo-bucket
      versioningConfiguration:
        Status: Enabled

functions:
  catchArchivedPhoto:
    role: arn:aws:iam::036003563447:role/demo-serverless-framework-lambda-role
    handler: index.handler
    events:
      - s3:
          bucket: demo-johndev4-photo-bucket
          event: s3:ObjectCreated:Copy
          rules:
            - prefix: Archives/
            - suffix: .jpg
          # existing: true
